### PR TITLE
Bump to 6.29.5

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
I need that exact 6.29.5 version for https://github.com/conda-forge/staged-recipes/pull/21653

**Comment by hadim** [comment]
@conda-forge/rocksdb do you mind reviewing please?

**Comment by hadim** [comment]
@hmaarrfk do you mind reviewing this since this repo seems a bit unmaintained? I added myself as a maintainer.

I need that exact version for another package, but I am happy to try to build the latest version once merged here.

Also I have a question: all the compression libs (zlib, bzip2, snappy, etc) are in `reqs/host`, I wonder whether we should add them to `reqs/run` as well so people using `rocksdb` does not have to include them specifically. What do you think?

**Comment by hmaarrfk** [comment]
They are implicitly added through run_export in the respective packages.

**Comment by hadim** [comment]
Thanks @hmaarrfk !

**Pull request merged**
