### PR TITLE
6.29.5

### PR DESCRIPTION
**Pull request by swenger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge/rocksdb could you create a `6.29.x` branch from https://github.com/conda-forge/rocksdb-feedstock/commit/222e430774aa8f12d95e46dd2e1d9df0b4efcfdc so we can merge this PR into that branch? Thanks!

### CODE REVIEW

**Comment by hadim** [comment]
> https://github.com/orgs/conda-forge/teams/rocksdb could you create a 6.29.x branch from https://github.com/conda-forge/rocksdb-feedstock/commit/222e430774aa8f12d95e46dd2e1d9df0b4efcfdc so we can merge this PR into that branch?

done

**Comment by swenger** [comment]
> > https://github.com/orgs/conda-forge/teams/rocksdb could you create a 6.29.x branch from [222e430](https://github.com/conda-forge/rocksdb-feedstock/commit/222e430774aa8f12d95e46dd2e1d9df0b4efcfdc) so we can merge this PR into that branch?
> 
> done

Thanks @hadim, that was fast!

Did you branch from https://github.com/conda-forge/rocksdb-feedstock/commit/222e430774aa8f12d95e46dd2e1d9df0b4efcfdc though, or from `main`? I suddenly see a lot of diffs that weren't there before.

**Comment by hadim** [comment]
I created the branch from https://github.com/conda-forge/rocksdb-feedstock/commit/222e430774aa8f12d95e46dd2e1d9df0b4efcfdc

**Comment by hadim** [comment]
Maybe it should be from 52664354d4e221bb65bf412a8556dba50b3c6432 actually. Let me check.

**Comment by hadim** [comment]
Ok it should be better now (I used the last commit of the 6.29.5 PR instead of the first one).

**Comment by swenger** [comment]
> Ok it should be better now (I used the last commit of the 6.29.5 PR instead of the first one).

Ah, that makes sense... Thanks, looks good now!

**Comment by hadim** [comment]
LGTM. Thanks.

**Comment by swenger** [comment]
Thanks @hadim!

**Pull request merged**
